nba_dw_project:
  outputs:
    dev:
      account: azb79167
      database: MLDS430
      private_key_passphrase: ''
      private_key_path: /usr/local/airflow/include/rsa_key.pem
      role: TRAINING_ROLE
      schema: MARMOT_FINAL
      threads: 1
      type: snowflake
      user: MARMOT
      warehouse: TRAINING_WH
  target: dev